name = "aics-api"
main = "src/index.js"
compatibility_date = "2026-01-01"

# --- Top-level (default when running `npx wrangler deploy` without --env) ---
vars = { ENVIRONMENT = "prod", ALLOWED_ORIGINS = "https://aics-api.saibaunglin808.workers.dev" }

[[d1_databases]]
binding = "DB"
database_name = "aics-db-prod"
database_id = "d073582b-3471-4120-a118-0194d4c2fb8f"

# --- dev ---
[env.dev]
vars = { ENVIRONMENT = "dev", ALLOWED_ORIGINS = "https://aics-frontend-dev.pages.dev" }
[[env.dev.d1_databases]]
binding = "DB"
database_name = "aics-db-dev"
database_id = "3f747286-9531-4b92-96a7-f0144387bd91"

# --- staging ---
[env.staging]
vars = { ENVIRONMENT = "staging", ALLOWED_ORIGINS = "https://aics-frontend-staging.pages.dev" }
[[env.staging.d1_databases]]
binding = "DB"
database_name = "aics-db-staging"
database_id = "7c663452-6270-4c73-9a2c-6cd1dee977f5"

# --- prod ---
[env.prod]
vars = { ENVIRONMENT = "prod", ALLOWED_ORIGINS = "https://aics-api.saibaunglin808.workers.dev" }
[[env.prod.d1_databases]]
binding = "DB"
database_name = "aics-db-prod"
database_id = "d073582b-3471-4120-a118-0194d4c2fb8f"
