name = "aics-api"
main = "src/index.js"
compatibility_date = "2026-01-01"

# --- dev ---
[env.dev]
vars = { ENVIRONMENT = "dev", ALLOWED_ORIGINS = "https://aics-frontend-dev.pages.dev" }
[[env.dev.d1_databases]]
binding = "DB"
database_name = "aics-db-dev"
database_id = "926877c3-c516-427d-8f95-36535e483bf5"

# --- staging ---
[env.staging]
vars = { ENVIRONMENT = "staging", ALLOWED_ORIGINS = "https://aics-frontend-staging.pages.dev" }
[[env.staging.d1_databases]]
binding = "DB"
database_name = "aics-db-staging"
database_id = "69cbd9a2-9460-4687-80d1-e86aa2995d9a"

# --- prod ---
[env.prod]
vars = { ENVIRONMENT = "prod", ALLOWED_ORIGINS = "https://aics-frontend-prod.pages.dev" }
[[env.prod.d1_databases]]
binding = "DB"
database_name = "aics-db-prod"
database_id = "d073582b-3471-4120-a118-0194d4c2fb8f"
